version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 832194895313.dkr.ecr.us-east-1.amazonaws.com)

      - IMAGE_REPO=832194895313.dkr.ecr.us-east-1.amazonaws.com/rag-my
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}

  build:
    commands:
      - echo Build Docker image...
      - docker build -t $IMAGE_REPO:$IMAGE_TAG .
      - docker tag $IMAGE_REPO:$IMAGE_TAG $IMAGE_REPO:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $IMAGE_REPO:$IMAGE_TAG
      - docker push $IMAGE_REPO:latest

      - printf '{"ImageURI":"%s:%s"}' $IMAGE_REPO $IMAGE_TAG > imageDetail.json

artifacts:
  files:
    - imageDetail.json
